### ISSUE TITLE
TimestampHelper还有大部分的Model都是乱码。。。谁有正常的

### ISSUE THREAD

**Issue by victory723** [guolaopi/WPSOnlineDemo#1]
TimestampHelper还有大部分的Model都是乱码。。。谁有正常的发来看看

**Comment by guolaopi** [comment]
@victory723 
可能被我电脑上的加密软件加密了。稍后我传一下新的，抱歉

**Comment by victory723** [comment]
> @victory723
> 可能被我电脑上的加密软件加密了。稍后我传一下新的，抱歉

嗯 没事 谢谢

**Comment by guolaopi** [comment]
@victory723 
刚提交了下，你更新下看看，抱歉带来麻烦了
